services:
  exchange-service:
    image: scfrancisco/exchange-service
    restart: always
    build:
      context: ./exchange-service
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/exchange_service?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
    ports:
      - 8000:8000
    networks:
      - erudio-network

  book-service:
    image: scfrancisco/book-service
    restart: always
    build:
      context: ./book-service
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/book_service?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
    ports:
      - 8100:8100
    networks:
      - erudio-network
networks:
  erudio-network:
    name: erudio-network
    driver: bridge