apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"4"},"creationTimestamp":"2025-12-26T15:01:22Z","generation":4,"labels":{"app":"exchange-service"},"name":"exchange-service","namespace":"default","resourceVersion":"1239","uid":"cc06e9b1-f14f-47b0-ae7f-0f6ec11ea9e6"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"exchange-service"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"2025-12-26T15:06:23Z"},"creationTimestamp":null,"labels":{"app":"exchange-service"}},"spec":{"containers":[{"env":[{"name":"SPRING_DATASOURCE_URL","value":"jdbc:mysql://host.docker.internal:3306/exchange_service"},{"name":"SPRING_DATASOURCE_USERNAME","value":"docker"},{"name":"SPRING_DATASOURCE_PASSWORD","value":"admin123"}],"image":"scfrancisco/exchange-service:kube-v1","imagePullPolicy":"IfNotPresent","name":"exchange-service","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2025-12-26T15:06:18Z","lastUpdateTime":"2025-12-26T15:06:18Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2025-12-26T15:01:22Z","lastUpdateTime":"2025-12-26T15:06:24Z","message":"ReplicaSet \"exchange-service-685c8c7c9d\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":4,"readyReplicas":1,"replicas":2,"updatedReplicas":1}}
  labels:
    app: exchange-service
  name: exchange-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exchange-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-12-26T15:06:23Z"
      labels:
        app: exchange-service
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://host.docker.internal:3306/exchange_service
        - name: SPRING_DATASOURCE_USERNAME
          value: docker
        - name: SPRING_DATASOURCE_PASSWORD
          value: admin123
        image: scfrancisco/exchange-service:kube-v1
        imagePullPolicy: IfNotPresent
        name: exchange-service
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: exchange-service
  name: exchange-service
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32730
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: exchange-service
  sessionAffinity: None
  type: LoadBalancer

